### ISSUE TITLE
correct weighting of pretrain_transformer.pth

### ISSUE THREAD

**Issue by albushuang** [csguoh/LEMMA#3]
Hi Guo Hang:

I failed to run test by command:

python3 main.py --test

The error messages are:
File "/home/work/project/LEMMA/loss/text_focus_loss.py", line 556, in build_up_transformer
    transformer.load_state_dict(torch.load(self.cfg.pretrained_trans))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Transformer:

My pretrain_transformer.pth was downloaded according to the link provide by this repo:
https://github.com/FudanVI/FudanOCR/tree/main/scene-text-telescope

What am I doing wrong?

Please kindly provide your opinion, thank you.

Albus

**Comment by csguoh** [comment]
Hi, Albus.
Since the pretrained weight of transformer in https://github.com/FudanVI/FudanOCR/tree/main/scene-text-telescope is a multi-gpu version, as you can see there is an attribute `.module` in the downloaded weight using the above link.
In our code implementation, we modify this pre-trained weight to adapt to single-gpu. I have uploaded this single-gpu version to google drive with this [link](https://drive.google.com/file/d/1HRpzveBbnJPQn3-k_y2Y1YY4PcraWOFP/view?usp=drive_link). You can directly use it to replace the original '.pth' file.

**Comment by albushuang** [comment]
Thank you, the issue is solved.
